name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the current rclone version
      run: RCLONEVERSION=$(curl -s https://downloads.rclone.org/v1.57.0/version.txt | cut -d" " -f2)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag h3po/rclone-alpine:${RCLONEVERSION}
